CREATE TABLE [dbo].[VALU_EXCEL_EXT_CONTENT](
	[ImportID] [int] NOT NULL,
	[EID] [int] NOT NULL,
	[ColumnName] [nvarchar](255) NULL,
	[Content] NVARCHAR(2048) NOT NULL, 
    CONSTRAINT [PK_VALU_EXCEL_EXT_CONTENT] PRIMARY KEY ([ImportID], [EID]), 
    CONSTRAINT [FK_VALU_EXCEL_EXT_CONTENT_EXCEL] FOREIGN KEY ([ImportID]) REFERENCES [VALU_EXCEL]([ID]),
	CONSTRAINT [FK_VALU_EXCEL_EXT_CONTENT_EXT] FOREIGN KEY ([EID]) REFERENCES [VALU_EXCEL_EXT]([ID])
)